"""default

Revision ID: 166dfd2a80a0
Revises: 865542306974
Create Date: 2023-03-31 17:36:57.972247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166dfd2a80a0'
down_revision = '865542306974'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
