"""ch_fields

Revision ID: 82edf2c46899
Revises: e293796db742
Create Date: 2023-03-31 19:37:54.194040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82edf2c46899'
down_revision = 'e293796db742'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_review_log', sa.Column('review_status', sa.Enum('got', 'loss'), nullable=True))
    op.drop_column('word_review_log', 'review_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_review_log', sa.Column('review_type', sa.VARCHAR(length=4), nullable=True))
    op.drop_column('word_review_log', 'review_status')
    # ### end Alembic commands ###
