"""add time

Revision ID: 865542306974
Revises: aebbd3824bbf
Create Date: 2023-03-31 17:33:09.670879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865542306974'
down_revision = 'aebbd3824bbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_list', sa.Column('create_date', sa.DATE(), nullable=True))
    op.add_column('word_list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('word_list', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_list', 'updated_at')
    op.drop_column('word_list', 'created_at')
    op.drop_column('word_list', 'create_date')
    # ### end Alembic commands ###
