"""mv_field

Revision ID: a42b3785b710
Revises: 82edf2c46899
Create Date: 2023-04-01 10:20:35.009698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42b3785b710'
down_revision = '82edf2c46899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('show_times', sa.Integer(), nullable=True),
    sa.Column('forget_times', sa.Integer(), nullable=True),
    sa.Column('remember_times', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_review_id'), 'word_review', ['id'], unique=False)
    op.drop_column('word_list', 'create_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_list', sa.Column('create_date', sa.DATE(), nullable=True))
    op.drop_index(op.f('ix_word_review_id'), table_name='word_review')
    op.drop_table('word_review')
    # ### end Alembic commands ###
