"""review log

Revision ID: e293796db742
Revises: 166dfd2a80a0
Create Date: 2023-03-31 17:57:55.167564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e293796db742'
down_revision = '166dfd2a80a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('review_type', sa.Enum('got', 'loss'), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_review_log_id'), 'word_review_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_review_log_id'), table_name='word_review_log')
    op.drop_table('word_review_log')
    # ### end Alembic commands ###
